services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: payclub
      POSTGRES_PASSWORD: wf,b6q)Y35cup;Ev}= 
      POSTGRES_DB: payclub
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge